---
# description: Configure telegraf

- name: "Copy the template"
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: "{{ telegraf_agent_config_path }}/telegraf.conf"
    owner: telegraf
    group: telegraf
    mode: '0640'
  become: true
  notify:
    - Restart Telegraf

- name: "Check if extra plugins directory exists in case of exclusive"
  ansible.builtin.stat:
    path: "{{ telegraf_agent_config_path }}/telegraf.d"
  register: telegraf_directory
  when:
    - telegraf_plugins_extra_exclusive

- name: "Delete telegraf extra plugin path"
  ansible.builtin.file:
    state: absent
    path: "{{ telegraf_agent_config_path }}/telegraf.d/"
  when:
    - telegraf_plugins_extra_exclusive
    - telegraf_directory.stat.exists
  become: true
  notify:
    - Restart Telegraf

- name: "Create telegraf extra plugin path"
  ansible.builtin.file:
    state: directory
    path: "{{ telegraf_agent_config_path }}/telegraf.d/"
    owner: telegraf
    group: telegraf
    mode: '0755'
  when:
    - telegraf_plugins_extra_exclusive
    - telegraf_directory.stat.exists
  become: true
  notify:
    - Restart Telegraf

- name: "Copy telegraf extra plugins"
  ansible.builtin.template:
    src: "telegraf-extra-plugin.conf.j2"
    dest: "{{ telegraf_agent_config_path }}/telegraf.d/{{ item.key }}.conf"
    owner: telegraf
    group: telegraf
    mode: '0640'
  with_dict: "{{ telegraf_plugins_extra }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - telegraf_plugins_extra is defined
    - telegraf_plugins_extra is iterable
    - item.value.state|default('present') != 'absent'
  become: true
  notify:
    - Restart Telegraf

- name: "Remove telegraf extra plugins"
  ansible.builtin.file:
    path: "{{ telegraf_agent_config_path }}/telegraf.d/{{ item.key }}.conf"
    state: absent
  with_dict: "{{ telegraf_plugins_extra }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - telegraf_plugins_extra is defined
    - telegraf_plugins_extra is iterable
    - item.value.state|default('present') == 'absent'
  become: true
  notify:
    - Restart Telegraf

- name: "Force restart service after reread config"
  ansible.builtin.meta: flush_handlers

- name: "Start Telegraf (If it wasn't running)"
  ansible.builtin.systemd_service:
    name: telegraf
    state: "{{ telegraf_enabled | ternary('started', 'stopped') }}"
    enabled: "{{ telegraf_enabled }}"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure system for for smart plugin
  when: "'smart' in telegraf_plugins_extra"
  block:
    - name: Install smartmontools
      become: true
      ansible.builtin.package:
        name: smartmontools

    - name: Find path of smartctl
      ansible.builtin.command: which smartctl
      register: which_smartctl
      ignore_errors: true
      changed_when: false
      become: true

    - name: Ensure telegraf user can execute smartctl
      ansible.builtin.blockinfile:
        marker: "# {mark} ANSIBLE MANAGED BLOCK (Ensure telegraf user can execute smartctl)"
        dest: "/etc/sudoers.d/telegraf"
        block: "telegraf ALL=(root) NOPASSWD: {{ which_smartctl.stdout }}"
        mode: '0400'
        create: true
      become: true
      notify:
        - Restart Telegraf


- name: Configure system for for sensors plugin
  when: "'sensors' in telegraf_plugins_extra"
  block:
    - name: Debian | Install lm-sensors
      ansible.builtin.package:
        name: lm-sensors
      become: true
      notify:
        - Restart Telegraf
      when: ansible_os_family == "Debian"
    - name: RedHat | Install lm-sensors
      ansible.builtin.package:
        name: lm_sensors
      become: true
      notify:
        - Restart Telegraf
      when: ansible_os_family == "RedHat"
