---

- name: "Debian | Set name if state != latest"
  ansible.builtin.set_fact:
    telegraf_agent_package: telegraf={{ telegraf_agent_version }}-{{ telegraf_agent_version_patch }}
  when:
    - telegraf_agent_package_state != "latest"

- name: "Debian | Set telegraf_agent_package_arch"
  ansible.builtin.set_fact:
    telegraf_agent_package_arch: "{{ ansible_architecture }}"

- name: "Debian | Set telegraf_agent_package_arch specific for x86_64"
  ansible.builtin.set_fact:
    telegraf_agent_package_arch: "amd64"
  when:
    - ansible_architecture == "x86_64"

- name: "Debian | Set telegraf_agent_package_arch specific for arm64"
  ansible.builtin.set_fact:
    telegraf_agent_package_arch: "armhf"
  when:
    - ansible_architecture == "arm64"

- name: "Debian | Ensure the system can use the HTTPS transport for APT"
  ansible.builtin.stat:
    path: /usr/lib/apt/methods/https
  register: apt_https_transport

- name: "Debian | Install APT HTTPS transport"
  ansible.builtin.apt:
    name: "apt-transport-https"
    state: present
  register: are_telegraf_dependencies_packages_installed
  until: are_telegraf_dependencies_packages_installed is succeeded
  when:
    - not apt_https_transport.stat.exists
  become: true

- name: "Debian | Configure Telegraf apt repository"
  block:
    - name: "Debian | Ensure the shared keyrings directory exists"
      ansible.builtin.stat:
        path: /usr/share/keyrings
      register: usr_share_keyrings

    - name: "Debian | Create shared keyrings directory"
      ansible.builtin.file:
        state: directory
        path: /usr/share/keyrings
        owner: root
        group: root
        mode: '0755'
      when:
        - not usr_share_keyrings.stat.exists
      become: true

    - name: "Debian | Install Telegraf apt key"
      ansible.builtin.get_url:
        url: https://repos.influxdata.com/influxdata-archive.key
        dest: /usr/share/keyrings/influxdata-archive.asc
        mode: '0644'
      register: are_telegraf_dependencies_keys_installed
      until: are_telegraf_dependencies_keys_installed is succeeded
      become: true

    - name: "Debian | Set Telegraf apt repository parameters"
      ansible.builtin.set_fact:
        telegraf_repository_params: "[signed-by=/usr/share/keyrings/influxdata-archive.asc]"

    - name: "Debian | Add Telegraf repository"
      ansible.builtin.copy:
        content: "deb https://repos.influxdata.com/{{ ansible_distribution | lower }} stable main"
        dest: /etc/apt/sources.list.d/telegraf.list
        mode: '0644'
      become: true

    - name: "Debian | Install Telegraf package (repo)"
      ansible.builtin.apt:
        name: "{{ telegraf_agent_package }}"
        state: "{{ telegraf_agent_package_state }}"
        update_cache: true
      register: is_telegraf_package_installed
      until: is_telegraf_package_installed is succeeded
      notify: "Restart Telegraf"
      become: true
      ignore_errors: "{{ ansible_check_mode }}"
