---
# tasks file for ansible-telegraf
#
- name: Telegraf is going to be deployed on the system
  when: telegraf_state != "absent"
  block:
    - name: "Install on RedHat"
      ansible.builtin.include_tasks: "RedHat.yml"
      when:
        - ansible_os_family == "RedHat"

    - name: "Install on Debian"
      ansible.builtin.include_tasks: "Debian.yml"
      when:
        - ansible_os_family == "Debian"

    - name: "Configure Telegraf"
      ansible.builtin.include_tasks: "configure.yml"

- name: Telegraf is going to be removed from the system
  ansible.builtin.include_tasks: "uninstall_{{ ansible_os_family }}.yml"
  when: telegraf_state == "absent"
