---
# description: RedHat specific installation

- name: "RedHat | Set name if state == latest"
  ansible.builtin.set_fact:
    telegraf_agent_package: telegraf-{{ telegraf_agent_version }}
  when:
    - telegraf_agent_package_state != "latest"

- name: "RedHat | Add yum repository"
  ansible.builtin.yum_repository:
    name: influxdb
    description: InfluxDB Repository
    baseurl: "{{ telegraf_yum_baseurl }}"
    gpgcheck: "{{ telegraf_yum_gpgcheck | default('true') }}"
    gpgkey: "{{ telegraf_yum_gpgkey }}"
  become: true

- name: "RedHat | Install Telegraf package"
  ansible.builtin.package:
    name: "{{ telegraf_agent_package }}"
    state: "{{ telegraf_agent_package_state }}"
  register: is_telegraf_package_installed
  until: is_telegraf_package_installed is succeeded
  become: true
  notify: "Restart Telegraf"
  ignore_errors: "{{ ansible_check_mode }}"
