---
# handlers file for ansible-telegraf

- name: "Restart Telegraf"
  ansible.builtin.systemd_service:
    name: telegraf
    state: restarted
    enabled: true
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
